### PR TITLE
Fix generated node js code

### PR DESCRIPTION
**Pull request by bracki**
@p0wl @timse 

Does this improve the situation?

Run:

```
./bootstrap.sh
./configure
cd compiler/cpp
make
./thrift -gen js:node FooService.thrift
```

### CODE REVIEW

**Comment by p0wl** [comment]
had to `brew install automake` and `brew install bison; brew unlink bison; brew link bison --force` before `./configure` worked.

generated code looks good! we now have a version problem :dancer: 

```
Uncaught TProtocolException: Bad version in readMessageBegin: -272646911
```

is this because the `npm install thrift` package version differs from our generated thrift?

**Comment by p0wl** [comment]
So we need to merge this and create a tag, right @bracki ?

**Comment by timse** [comment]
i think we just need to update thrift no?
this is live in thrift

**Comment by bracki** [comment]
We'll need to incorporate https://github.com/apache/thrift/pull/707.patch or just use [Docker](https://github.com/apache/thrift/blob/master/Dockerfile#L22).

Just merging into `master` won't work. The patch needs to be applied against `0.9.2.jimdo2`.
Just using `1.0.0` won't work either, because it has to compile on Debian Squeeze.

**Comment by timse** [comment]
sounds fun!

**Comment by p0wl** [comment]
okay!

**Comment by bracki** [comment]
🤓🥳

**Pull request closed without merging**
